export const WORDS = [
    {
        id: 1,
        en: "bored",
        nl: "verveeld",
        direction: "nl-en",      // of "en-nl"
        skill: "productief",     // of "receptief"
    },
    {
        id: 2,
        en: "culture",
        nl: "cultuur",
        direction: "nl-en",
        skill: "productief",
    },
    {
        id: 3,
        en: "gold",
        nl: "goud",
        direction: "nl-en",
        skill: "productief",
    },
    {
        id: 4,
        en: "to paint",
        nl: "schilderen",
        direction: "nl-en",
        skill: "productief",
    },
    {
        id: 5,
        en: "to prefer",
        nl: "voorkeur geven aan",
        direction: "nl-en",
        skill: "productief",
    },
    {
        id: 6,
        en: "probably",
        nl: "waarschijnlijk",
        direction: "nl-en",
        skill: "productief",
    },
    {
        id: 7,
        en: "ride",
        nl: "attractie",
        direction: "nl-en",
        skill: "productief",
    },
    {
        id: 8,
        en: "to serve",
        nl: "serveren",
        direction: "nl-en",
        skill: "productief",
    },
    {
        id: 9,
        en: "somewhere",
        nl: "ergens",
        direction: "nl-en",
        skill: "productief",
    },
    {
        id: 10,
        en: "to sweat",
        nl: "zweten",
        direction: "nl-en",
        skill: "productief",
    },
    {
        id: 11,
        en: "tiny",
        nl: "heel klein",
        direction: "nl-en",
        skill: "productief",
    },
    {
        id: 12,
        en: "frame",
        nl: "lijst",
        direction: "en-nl",
        skill: "receptief",
    },
    {
        id: 13,
        en: "portrait",
        nl: "portret",
        direction: "en-nl",
        skill: "receptief",
    },
    {
        id: 14,
        en: "tank",
        nl: "aquarium",
        direction: "en-nl",
        skill: "receptief",
    },
    {
        id: 15,
        en: "to vomit",
        nl: "overgeven",
        direction: "en-nl",
        skill: "receptief",
    },
    {
        id: 16,
        en: "cosy",
        nl: "gezellig",
        direction: "nl-en",
        skill: "productief",
    },
    {
        id: 17,
        en: "decide",
        nl: "beslissen",
        direction: "nl-en",
        skill: "productief",
    },
    {
        id: 18,
        en: "delicious",
        nl: "heerlijk",
        direction: "nl-en",
        skill: "productief",
    },
    {
        id: 19,
        en: "fashion",
        nl: "mode",
        direction: "nl-en",
        skill: "productief",
    },
    {
        id: 20,
        en: "hill",
        nl: "heuvel",
        direction: "nl-en",
        skill: "productief",
    },
    {
        id: 21,
        en: "incredible",
        nl: "ongelofelijk",
        direction: "nl-en",
        skill: "productief",
    },
    {
        id: 22,
        en: "loud",
        nl: "hard",
        direction: "nl-en",
        skill: "productief",
    },
    {
        id: 23,
        en: "noise",
        nl: "lawaai",
        direction: "nl-en",
        skill: "productief",
    },
    {
        id: 24,
        en: "scary",
        nl: "eng",
        direction: "nl-en",
        skill: "productief",
    },
    {
        id: 25,
        en: "view",
        nl: "uitzicht",
        direction: "nl-en",
        skill: "productief",
    },
    {
        id: 26,
        en: "bike lane",
        nl: "fietspad",
        direction: "en-nl",
        skill: "receptief",
    },
    {
        id: 27,
        en: "definitely",
        nl: "absoluut",
        direction: "en-nl",
        skill: "receptief",
    },
    {
        id: 28,
        en: "explore",
        nl: "onderzoeken",
        direction: "en-nl",
        skill: "receptief",
    },
    {
        id: 29,
        en: "several",
        nl: "verschillende",
        direction: "en-nl",
        skill: "receptief",
    },
    {
        id: 30,
        en: "to compare",
        nl: "vergelijken met",
        direction: "nl-en",
        skill: "productief",
    },
    {
        id: 31,
        en: "cushion",
        nl: "kussen",
        direction: "nl-en",
        skill: "productief",
    },
    {
        id: 32,
        en: "floor",
        nl: "verdieping",
        direction: "nl-en",
        skill: "productief",
    },
    {
        id: 33,
        en: "island",
        nl: "eiland",
        direction: "nl-en",
        skill: "productief",
    },
    {
        id: 34,
        en: "luckily",
        nl: "gelukkig",
        direction: "nl-en",
        skill: "productief",
    },
    {
        id: 35,
        en: "prepared",
        nl: "voorbereid",
        direction: "nl-en",
        skill: "productief",
    },
    {
        id: 36,
        en: "protect",
        nl: "beschermen",
        direction: "nl-en",
        skill: "productief",
    },
    {
        id: 37,
        en: "shade",
        nl: "schaduw",
        direction: "nl-en",
        skill: "productief",
    },
    {
        id: 38,
        en: "tradition",
        nl: "traditie",
        direction: "nl-en",
        skill: "productief",
    },
    {
        id: 39,
        en: "unique",
        nl: "uniek",
        direction: "nl-en",
        skill: "productief",
    },
    {
        id: 40,
        en: "boiling hot",
        nl: "gloeiend heet",
        direction: "en-nl",
        skill: "receptief",
    },
    {
        id: 41,
        en: "considering",
        nl: "gezien het feit dat",
        direction: "en-nl",
        skill: "receptief",
    },
    {
        id: 42,
        en: "get the hang of something",
        nl: "iets onder de knie krijgen",
        direction: "en-nl",
        skill: "receptief",
    },
    {
        id: 43,
        en: "moody",
        nl: "humeurig",
        direction: "en-nl",
        skill: "receptief",
    },
    {
        id: 44,
        en: "slightly",
        nl: "een beetje",
        direction: "en-nl",
        skill: "receptief",
    },
    {
        id: 45,
        en: "actually",
        nl: "eigenlijk",
        direction: "nl-en",
        skill: "productief",
    },
    {
        id: 46,
        en: "to climb",
        nl: "klimmen",
        direction: "nl-en",
        skill: "productief",
    },
    {
        id: 47,
        en: "fake",
        nl: "nep",
        direction: "nl-en",
        skill: "productief",
    },
    {
        id: 48,
        en: "flag",
        nl: "vlag",
        direction: "nl-en",
        skill: "productief",
    },
    {
        id: 49,
        en: "pretend",
        nl: "doen alsof",
        direction: "nl-en",
        skill: "productief",
    },
    {
        id: 50,
        en: "to reach",
        nl: "bereiken",
        direction: "nl-en",
        skill: "productief",
    },
    {
        id: 51,
        en: "realise",
        nl: "zich realiseren",
        direction: "nl-en",
        skill: "productief",
    },
    {
        id: 52,
        en: "rock",
        nl: "rots",
        direction: "nl-en",
        skill: "productief",
    },
    {
        id: 53,
        en: "save",
        nl: "redden",
        direction: "nl-en",
        skill: "productief",
    },
    {
        id: 54,
        en: "shadow",
        nl: "schaduw",
        direction: "nl-en",
        skill: "productief",
    },
    {
        id: 55,
        en: "terrifying",
        nl: "angstaanjagend",
        direction: "nl-en",
        skill: "productief",
    },
    {
        id: 56,
        en: "upside down",
        nl: "ondersteboven",
        direction: "nl-en",
        skill: "productief",
    },
    {
        id: 57,
        en: "to pose",
        nl: "poseren",
        direction: "en-nl",
        skill: "receptief",
    },
    {
        id: 58,
        en: "to trick",
        nl: "bedriegen",
        direction: "en-nl",
        skill: "receptief",
    },
    {
        id: 59,
        en: "truth",
        nl: "waarheid",
        direction: "en-nl",
        skill: "receptief",
    },
    {
        id: 60,
        en: "travelling",
        nl: "reizen",
        direction: "nl-en",
        skill: "productief",
    },
    {
        id: 61,
        en: "packing your suitcase",
        nl: "je koffer inpakken",
        direction: "nl-en",
        skill: "productief",
    },
    {
        id: 62,
        en: "to board",
        nl: "instappen",
        direction: "nl-en",
        skill: "productief",
    },
    {
        id: 63,
        en: "abroad",
        nl: "naar het buitenland",
        direction: "nl-en",
        skill: "productief",
    },
    {
        id: 64,
        en: "airport",
        nl: "luchthaven",
        direction: "nl-en",
        skill: "productief",
    },
    {
        id: 65,
        en: "arrival",
        nl: "aankomst",
        direction: "nl-en",
        skill: "productief",
    },
    {
        id: 66,
        en: "backpack",
        nl: "rugzak",
        direction: "nl-en",
        skill: "productief",
    },
    {
        id: 67,
        en: "beach towel",
        nl: "strandhanddoek",
        direction: "nl-en",
        skill: "productief",
    },
    {
        id: 68,
        en: "border",
        nl: "grens",
        direction: "nl-en",
        skill: "productief",
    },
    {
        id: 69,
        en: "campsite",
        nl: "camping",
        direction: "nl-en",
        skill: "productief",
    },
    {
        id: 70,
        en: "charger",
        nl: "oplader",
        direction: "nl-en",
        skill: "productief",
    },
    {
        id: 71,
        en: "check-in",
        nl: "incheckbalie",
        direction: "nl-en",
        skill: "productief",
    },
    {
        id: 72,
        en: "customs",
        nl: "douane",
        direction: "nl-en",
        skill: "productief",
    },
    {
        id: 73,
        en: "departure",
        nl: "vertrek",
        direction: "nl-en",
        skill: "productief",
    },
    {
        id: 74,
        en: "destination",
        nl: "bestemming",
        direction: "nl-en",
        skill: "productief",
    },
    {
        id: 75,
        en: "flight",
        nl: "vlucht",
        direction: "nl-en",
        skill: "productief",
    },
    {
        id: 75,
        en: "flight",
        nl: "vlucht",
        direction: "nl-en",
        skill: "productief",
    },
    {
        id: 76,
        en: "flip-flops",
        nl: "teenslippers",
        direction: "nl-en",
        skill: "productief",
    },
    {
        id: 77,
        en: "headphones",
        nl: "koptelefoon",
        direction: "nl-en",
        skill: "productief",
    },
    {
        id: 78,
        en: "luggage",
        nl: "bagage",
        direction: "nl-en",
        skill: "productief",
    },
    {
        id: 79,
        en: "passport",
        nl: "paspoort",
        direction: "nl-en",
        skill: "productief",
    },
    {
        id: 80,
        en: "rain coat",
        nl: "regenjas",
        direction: "nl-en",
        skill: "productief",
    },
    {
        id: 81,
        en: "sleeping bag",
        nl: "slaapzak",
        direction: "nl-en",
        skill: "productief",
    },
    {
        id: 82,
        en: "sunglasses",
        nl: "zonnebril",
        direction: "nl-en",
        skill: "productief",
    },
    {
        id: 83,
        en: "sunscreen",
        nl: "zonnebrandcrème",
        direction: "nl-en",
        skill: "productief",
    },
    {
        id: 84,
        en: "swimwear",
        nl: "badkleding",
        direction: "nl-en",
        skill: "productief",
    },
    {
        id: 85,
        en: "to take off",
        nl: "vertrekken",
        direction: "nl-en",
        skill: "productief",
    },
    {
        id: 86,
        en: "toothbrush",
        nl: "tandenborstel",
        direction: "nl-en",
        skill: "productief",
    },
    {
        id: 87,
        en: "toothpaste",
        nl: "tandpasta",
        direction: "nl-en",
        skill: "productief",
    },
    {
        id: 88,
        en: "travel guide",
        nl: "reisgids",
        direction: "nl-en",
        skill: "productief",
    },
    {
        id: 89,
        en: "trip",
        nl: "tocht",
        direction: "nl-en",
        skill: "productief",
    },
    {
        id: 90,
        en: "holiday activities",
        nl: "vakantieactiviteiten",
        direction: "nl-en",
        skill: "productief",
    },
    {
        id: 91,
        en: "to go backpacking",
        nl: "gaan rondtrekken",
        direction: "nl-en",
        skill: "productief",
    },
    {
        id: 92,
        en: "to go camping",
        nl: "gaan kamperen",
        direction: "nl-en",
        skill: "productief",
    },
    {
        id: 93,
        en: "to go sightseeing",
        nl: "bezienswaardigheden bezoeken",
        direction: "nl-en",
        skill: "productief",
    },
    {
        id: 94,
        en: "to hike",
        nl: "wandelen",
        direction: "nl-en",
        skill: "productief",
    },
    {
        id: 95,
        en: "to hit the beach",
        nl: "naar het strand gaan",
        direction: "nl-en",
        skill: "productief",
    },
    {
        id: 96,
        en: "to pitch your tent",
        nl: "je tent opzetten",
        direction: "nl-en",
        skill: "productief",
    },
    {
        id: 97,
        en: "to rent a bike",
        nl: "een fiets huren",
        direction: "nl-en",
        skill: "productief",
    },
    {
        id: 98,
        en: "to sign up for",
        nl: "inschrijven voor",
        direction: "nl-en",
        skill: "productief",
    },
    {
        id: 99,
        en: "to stay at",
        nl: "logeren",
        direction: "nl-en",
        skill: "productief",
    },
    {
        id: 100,
        en: "to sunbathe",
        nl: "zonnebaden",
        direction: "nl-en",
        skill: "productief",
    },
    {
        id: 101,
        en: "to take a dip",
        nl: "een duik nemen",
        direction: "nl-en",
        skill: "productief",
    },
    {
        id: 102,
        en: "to take a guided tour",
        nl: "een rondleiding krijgen",
        direction: "nl-en",
        skill: "productief",
    },
    {
        id: 103,
        en: "to take a picture",
        nl: "een foto maken",
        direction: "nl-en",
        skill: "productief",
    },
    {
        id: 104,
        en: "the weather",
        nl: "het weer",
        direction: "nl-en",
        skill: "productief",
    },
    {
        id: 105,
        en: "bright",
        nl: "helder",
        direction: "nl-en",
        skill: "productief",
    },
    {
        id: 106,
        en: "clear",
        nl: "helder",
        direction: "nl-en",
        skill: "productief",
    },
    {
        id: 107,
        en: "cloudy",
        nl: "bewolkt",
        direction: "nl-en",
        skill: "productief",
    },
    {
        id: 108,
        en: "fog",
        nl: "mist",
        direction: "nl-en",
        skill: "productief",
    },
    {
        id: 109,
        en: "hail",
        nl: "hagel",
        direction: "nl-en",
        skill: "productief",
    },
    {
        id: 110,
        en: "hurricane",
        nl: "orkaan",
        direction: "nl-en",
        skill: "productief",
    },
    {
        id: 111,
        en: "lightning",
        nl: "bliksem",
        direction: "nl-en",
        skill: "productief",
    },
    {
        id: 112,
        en: "rainbow",
        nl: "regenboog",
        direction: "nl-en",
        skill: "productief",
    },
    {
        id: 113,
        en: "rainy",
        nl: "regenachtig",
        direction: "nl-en",
        skill: "productief",
    },
    {
        id: 114,
        en: "rain shower",
        nl: "regenbui",
        direction: "nl-en",
        skill: "productief",
    },
    {
        id: 115,
        en: "stormy",
        nl: "stormachtig",
        direction: "nl-en",
        skill: "productief",
    },
    {
        id: 116,
        en: "sunny",
        nl: "zonnig",
        direction: "nl-en",
        skill: "productief",
    },
    {
        id: 117,
        en: "thunder",
        nl: "donder",
        direction: "nl-en",
        skill: "productief",
    },
    {
        id: 118,
        en: "windy",
        nl: "winderig",
        direction: "nl-en",
        skill: "productief",
    },
    // Chapter 2
    {
        id: 119,
        en: "a little bit",
        nl: "een klein beetje",
        direction: "nl-en",
        skill: "productief",
    },
    {
        id: 120,
        en: "to be honest",
        nl: "om eerlijk te zijn",
        direction: "nl-en",
        skill: "productief",
    },
    {
        id: 121,
        en: "building",
        nl: "gebouw",
        direction: "nl-en",
        skill: "productief",
    },
    {
        id: 122,
        en: "easy",
        nl: "kalm aan",
        direction: "nl-en",
        skill: "productief",
    },
    {
        id: 123,
        en: "to happen",
        nl: "gebeuren",
        direction: "nl-en",
        skill: "productief",
    },
    {
        id: 124,
        en: "memory",
        nl: "herinnering",
        direction: "nl-en",
        skill: "productief",
    },
    {
        id: 125,
        en: "pressure",
        nl: "druk",
        direction: "nl-en",
        skill: "productief",
    },
    {
        id: 126,
        en: "to promise",
        nl: "beloven",
        direction: "nl-en",
        skill: "productief",
    },
    {
        id: 127,
        en: "rather",
        nl: "liever",
        direction: "nl-en",
        skill: "productief",
    },
    {
        id: 128,
        en: "to stand",
        nl: "staan",
        direction: "nl-en",
        skill: "productief",
    },
    {
        id: 129,
        en: "thankfully",
        nl: "gelukkig",
        direction: "nl-en",
        skill: "productief",
    },
    {
        id: 130,
        en: "to believe",
        nl: "geloven",
        direction: "nl-en",
        skill: "productief",
    },
    {
        id: 131,
        en: "to cry",
        nl: "huilen",
        direction: "nl-en",
        skill: "productief",
    },
    {
        id: 132,
        en: "exactly",
        nl: "precies",
        direction: "nl-en",
        skill: "productief",
    },
    {
        id: 133,
        en: "to get up",
        nl: "opstaan",
        direction: "nl-en",
        skill: "productief",
    },
    {
        id: 134,
        en: "immediately",
        nl: "onmiddelijk",
        direction: "nl-en",
        skill: "productief",
    },
    {
        id: 135,
        en: "to protect",
        nl: "beschermen",
        direction: "nl-en",
        skill: "productief",
    },
    {
        id: 136,
        en: "reaction",
        nl: "reactie",
        direction: "nl-en",
        skill: "productief",
    },
    {
        id: 137,
        en: "side",
        nl: "kant",
        direction: "nl-en",
        skill: "productief",
    },
    {
        id: 138,
        en: "to smile",
        nl: "glimlachen",
        direction: "nl-en",
        skill: "productief",
    },
    {
        id: 139,
        en: "to warn",
        nl: "waarschuwen",
        direction: "nl-en",
        skill: "productief",
    },
    {
        id: 140,
        en: "weak",
        nl: "zwak",
        direction: "nl-en",
        skill: "productief",
    },
    {
        id: 141,
        en: "to wish",
        nl: "wensen",
        direction: "nl-en",
        skill: "productief",
    },
    {
        id: 142,
        en: "advice",
        nl: "advies",
        direction: "nl-en",
        skill: "productief",
    },
    {
        id: 143,
        en: "to agree",
        nl: "het eens zijn",
        direction: "nl-en",
        skill: "productief",
    },
    {
        id: 144,
        en: "to allow",
        nl: "toestaan",
        direction: "nl-en",
        skill: "productief",
    },
    {
        id: 145,
        en: "brain",
        nl: "hersenen",
        direction: "nl-en",
        skill: "productief",
    },
    {
        id: 146,
        en: "to calm down",
        nl: "rustig worden",
        direction: "nl-en",
        skill: "productief",
    },
    {
        id: 147,
        en: "to chew",
        nl: "kauwen",
        direction: "nl-en",
        skill: "productief",
    },
    {
        id: 148,
        en: "to concentrate",
        nl: "zich concentreren",
        direction: "nl-en",
        skill: "productief",
    },
    {
        id: 149,
        en: "honestly",
        nl: "eerlijk gezegd",
        direction: "nl-en",
        skill: "productief",
    },
    {
        id: 150,
        en: "horrible",
        nl: "vreselijk",
        direction: "nl-en",
        skill: "productief",
    },
    {
        id: 151,
        en: "to realise",
        nl: "zich realiseren",
        direction: "nl-en",
        skill: "productief",
    },
    {
        id: 152,
        en: "usually",
        nl: "gewoonlijk",
        direction: "nl-en",
        skill: "productief",
    },
    {
        id: 153,
        en: "to wake up",
        nl: "wakker worden",
        direction: "nl-en",
        skill: "productief",
    },
    {
        id: 154,
        en: "challenge",
        nl: "uitdaging",
        direction: "nl-en",
        skill: "productief",
    },
    {
        id: 155,
        en: "compare to",
        nl: "vergelijken met",
        direction: "nl-en",
        skill: "productief",
    },
    {
        id: 156,
        en: "to cycle",
        nl: "fietsen",
        direction: "nl-en",
        skill: "productief",
    },
    {
        id: 157,
        en: "to exist",
        nl: "bestaan",
        direction: "nl-en",
        skill: "productief",
    },
    {
        id: 158,
        en: "opposite",
        nl: "tegenovergesteld",
        direction: "nl-en",
        skill: "productief",
    },
    {
        id: 159,
        en: "planet",
        nl: "planeet",
        direction: "nl-en",
        skill: "productief",
    },
    {
        id: 160,
        en: "to share",
        nl: "delen",
        direction: "nl-en",
        skill: "productief",
    },
    {
        id: 161,
        en: "solution",
        nl: "oplossing",
        direction: "nl-en",
        skill: "productief",
    },
    {
        id: 162,
        en: "true",
        nl: "waar",
        direction: "nl-en",
        skill: "productief",
    },
    {
        id: 163,
        en: "to work out",
        nl: "trainen",
        direction: "nl-en",
        skill: "productief",
    },
    {
        id: 164,
        en: "to focus",
        nl: "zich concentreren",
        direction: "en-nl",
        skill: "receptief",
    },
    {
        id: 165,
        en: "hang on a minute",
        nl: "even wachten",
        direction: "en-nl",
        skill: "receptief",
    },
    {
        id: 166,
        en: "manage",
        nl: "aankunnen",
        direction: "en-nl",
        skill: "receptief",
    },
    {
        id: 167,
        en: "upsy-daisy",
        nl: "hupsakee",
        direction: "en-nl",
        skill: "receptief",
    },
    {
        id: 168,
        en: "purpose",
        nl: "doel",
        direction: "en-nl",
        skill: "receptief",
    },
    {
        id: 169,
        en: "recently",
        nl: "onlangs",
        direction: "en-nl",
        skill: "receptief",
    },
    {
        id: 170,
        en: "treatment",
        nl: "behandeling",
        direction: "en-nl",
        skill: "receptief",
    },
    {
        id: 171,
        en: "to cope",
        nl: "aankunnen",
        direction: "en-nl",
        skill: "receptief",
    },
    {
        id: 172,
        en: "to mind",
        nl: "erg vinden",
        direction: "en-nl",
        skill: "receptief",
    },
    {
        id: 173,
        en: "unusual",
        nl: "ongewoon",
        direction: "en-nl",
        skill: "receptief",
    },
    {
        id: 174,
        en: "achievement",
        nl: "prestatie",
        direction: "en-nl",
        skill: "receptief",
    },
    {
        id: 175,
        en: "insecure",
        nl: "onzeker",
        direction: "en-nl",
        skill: "receptief",
    },
    {
        id: 176,
        en: "instead of",
        nl: "in plaats van",
        direction: "en-nl",
        skill: "receptief",
    },
    {
        id: 177,
        en: "participant",
        nl: "deelnemer",
        direction: "en-nl",
        skill: "receptief",
    },
    {
        id: 178,
        en: "to retire",
        nl: "met pensioen gaan",
        direction: "en-nl",
        skill: "receptief",
    },
    {
        id: 179,
        en: "at the doctor's",
        nl: "bij de dokter",
        direction: "nl-en",
        skill: "productief",
    },
    {
        id: 180,
        en: "illness and injury",
        nl: "ziekte en verwondingen",
        direction: "nl-en",
        skill: "productief",
    },
    {
        id: 181,
        en: "appointment",
        nl: "afspraak",
        direction: "nl-en",
        skill: "productief",
    },
    {
        id: 182,
        en: "to be ill",
        nl: "ziek zijn",
        direction: "nl-en",
        skill: "productief",
    },
    {
        id: 182,
        en: "to bleed",
        nl: "bloeden",
        direction: "nl-en",
        skill: "productief",
    },
    {
        id: 183,
        en: "to bruise",
        nl: "kneuzen",
        direction: "nl-en",
        skill: "productief",
    },
    {
        id: 184,
        en: "to bump",
        nl: "stoten",
        direction: "nl-en",
        skill: "productief",
    },
    {
        id: 185,
        en: "to burn",
        nl: "branden",
        direction: "nl-en",
        skill: "productief",
    },
    {
        id: 186,
        en: "to cough",
        nl: "hoesten",
        direction: "nl-en",
        skill: "productief",
    },
    {
        id: 187,
        en: "crutches",
        nl: "krukken",
        direction: "nl-en",
        skill: "productief",
    },
    {
        id: 188,
        en: "to cut",
        nl: "snijden",
        direction: "nl-en",
        skill: "productief",
    },
    {
        id: 189,
        en: "dentist",
        nl: "tandarts",
        direction: "nl-en",
        skill: "productief",
    },
    {
        id: 190,
        en: "to examine",
        nl: "onderzoeken",
        direction: "nl-en",
        skill: "productief",
    },
    {
        id: 191,
        en: "to faint",
        nl: "flauwvallen",
        direction: "nl-en",
        skill: "productief",
    },
    {
        id: 192,
        en: "to feel sick",
        nl: "misselijk voelen",
        direction: "nl-en",
        skill: "productief",
    },
    {
        id: 193,
        en: "to feel worse",
        nl: "slechter voelen",
        direction: "nl-en",
        skill: "productief",
    },
    {
        id: 194,
        en: "fracture",
        nl: "breuk",
        direction: "nl-en",
        skill: "productief",
    },
    {
        id: 195,
        en: "to get better",
        nl: "beter worden",
        direction: "nl-en",
        skill: "productief",
    },
    {
        id: 196,
        en: "GP",
        nl: "huisarts",
        direction: "nl-en",
        skill: "productief",
    },
    {
        id: 197,
        en: "to hurt",
        nl: "pijn doen",
        direction: "nl-en",
        skill: "productief",
    },
    {
        id: 198,
        en: "to itch",
        nl: "jeuken",
        direction: "nl-en",
        skill: "productief",
    },
    {
        id: 199,
        en: "plaster",
        nl: "pleister",
        direction: "nl-en",
        skill: "productief",
    },
    {
        id: 200,
        en: "band-aid",
        nl: "pleister",
        direction: "nl-en",
        skill: "productief",
    },
    {
        id: 201,
        en: "to scratch",
        nl: "krabben",
        direction: "nl-en",
        skill: "productief",
    },
    {
        id: 202,
        en: "to slip",
        nl: "glijden",
        direction: "nl-en",
        skill: "productief",
    },
    {
        id: 203,
        en: "stitches",
        nl: "hechtingen",
        direction: "nl-en",
        skill: "productief",
    },
    {
        id: 204,
        en: "to stress out",
        nl: "stressen",
        direction: "nl-en",
        skill: "productief",
    },
    {
        id: 205,
        en: "to throw up",
        nl: "braken",
        direction: "nl-en",
        skill: "productief",
    },
    {
        id: 206,
        en: "to treat",
        nl: "behandelen",
        direction: "nl-en",
        skill: "productief",
    },
    {
        id: 207,
        en: "waiting room",
        nl: "wachtkamer",
        direction: "nl-en",
        skill: "productief",
    },
    {
        id: 208,
        en: "X-ray",
        nl: "röntgenfoto",
        direction: "nl-en",
        skill: "productief",
    },
    {
        id: 209,
        en: "health conditions",
        nl: "aandoeningen",
        direction: "nl-en",
        skill: "productief",
    },
    {
        id: 210,
        en: "black eye",
        nl: "blauw oog",
        direction: "nl-en",
        skill: "productief",
    },
    {
        id: 211,
        en: "to feel dizzy",
        nl: "duizelig zijn",
        direction: "nl-en",
        skill: "productief",
    },
    {
        id: 212,
        en: "to feel miserable",
        nl: "ellendig voelen",
        direction: "nl-en",
        skill: "productief",
    },
    {
        id: 213,
        en: "to have a cold",
        nl: "verkouden zijn",
        direction: "nl-en",
        skill: "productief",
    },
    {
        id: 214,
        en: "to have a fever",
        nl: "koorts hebben",
        direction: "nl-en",
        skill: "productief",
    },
    {
        id: 215,
        en: "to have a temperature",
        nl: "verhoging hebben",
        direction: "nl-en",
        skill: "productief",
    },
    {
        id: 216,
        en: "to have the flu",
        nl: "de griep hebben",
        direction: "nl-en",
        skill: "productief",
    },
    {
        id: 217,
        en: "headache",
        nl: "hoofdpijn",
        direction: "nl-en",
        skill: "productief",
    },
    {
        id: 218,
        en: "infection",
        nl: "infectie",
        direction: "nl-en",
        skill: "productief",
    },
    {
        id: 219,
        en: "to look pale",
        nl: "er bleek uitzien",
        direction: "nl-en",
        skill: "productief",
    },
    {
        id: 220,
        en: "runny nose",
        nl: "loopneus",
        direction: "nl-en",
        skill: "productief",
    },
    {
        id: 221,
        en: "sore throat",
        nl: "keelpijn",
        direction: "nl-en",
        skill: "productief",
    },
    {
        id: 222,
        en: "stomach ache",
        nl: "buikpijn",
        direction: "nl-en",
        skill: "productief",
    },
    {
        id: 223,
        en: "toothache",
        nl: "kiespijn",
        direction: "nl-en",
        skill: "productief",
    },
    {
        id: 224,
        en: "tips and advice",
        nl: "tips en advies",
        direction: "nl-en",
        skill: "productief",
    },
    {
        id: 225,
        en: "to avoid",
        nl: "vermijden",
        direction: "nl-en",
        skill: "productief",
    },
    {
        id: 226,
        en: "to breathe in",
        nl: "inademen",
        direction: "nl-en",
        skill: "productief",
    },
    {
        id: 227,
        en: "to cure",
        nl: "genezen",
        direction: "nl-en",
        skill: "productief",
    },
    {
        id: 228,
        en: "to cut down on",
        nl: "minderen",
        direction: "nl-en",
        skill: "productief",
    },
    {
        id: 229,
        en: "to hang in there",
        nl: "volhouden",
        direction: "nl-en",
        skill: "productief",
    },
    {
        id: 230,
        en: "to heal",
        nl: "herstellen",
        direction: "nl-en",
        skill: "productief",
    },
    {
        id: 231,
        en: "to improve",
        nl: "verbeteren",
        direction: "nl-en",
        skill: "productief",
    },
    {
        id: 232,
        en: "to push yourself",
        nl: "het beste uit jezelf halen",
        direction: "nl-en",
        skill: "productief",
    },
    {
        id: 233,
        en: "to quit",
        nl: "ophouden",
        direction: "nl-en",
        skill: "productief",
    },
    {
        id: 230,
        en: "to recover",
        nl: "herstellen",
        direction: "nl-en",
        skill: "productief",
    },
    {
        id: 231,
        en: "to rest",
        nl: "rusten",
        direction: "nl-en",
        skill: "productief",
    },
    {
        id: 232,
        en: "to take a break",
        nl: "een pauze nemen",
        direction: "nl-en",
        skill: "productief",
    },
    {
        id: 233,
        en: "to take it easy",
        nl: "het rustig aan doen",
        direction: "nl-en",
        skill: "productief",
    },
    {
        id: 234,
        en: "to worry",
        nl: "je zorgen maken",
        direction: "nl-en",
        skill: "productief",
    },
    {
        id: 235,
        en: "anything",
        nl: "wat je maar wilt",
        direction: "nl-en",
        skill: "productief",
    },
    {
        id: 235,
        en: "care",
        nl: "schelen",
        direction: "nl-en",
        skill: "productief",
    },
    {
        id: 236,
        en: "constantly",
        nl: "steeds",
        direction: "nl-en",
        skill: "productief",
    },
    {
        id: 237,
        en: "crowd",
        nl: "publiek",
        direction: "nl-en",
        skill: "productief",
    },
    {
        id: 238,
        en: "event",
        nl: "evenement",
        direction: "nl-en",
        skill: "productief",
    },
    {
        id: 239,
        en: "excited",
        nl: "opgewonden",
        direction: "nl-en",
        skill: "productief",
    },
    {
        id: 240,
        en: "insane",
        nl: "te gek",
        direction: "nl-en",
        skill: "productief",
    },
    {
        id: 241,
        en: "luckily",
        nl: "gelukkig",
        direction: "nl-en",
        skill: "productief",
    },
    {
        id: 242,
        en: "meet",
        nl: "ontmoeten",
        direction: "nl-en",
        skill: "productief",
    },
    {
        id: 243,
        en: "nearly",
        nl: "bijna",
        direction: "nl-en",
        skill: "productief",
    },
    {
        id: 244,
        en: "to remember",
        nl: "zich herinneren",
        direction: "nl-en",
        skill: "productief",
    },
    {
        id: 245,
        en: "charity",
        nl: "goed doel",
        direction: "en-nl",
        skill: "receptief",
    },
    {
        id: 246,
        en: "gem",
        nl: "juweel",
        direction: "en-nl",
        skill: "receptief",
    },
    {
        id: 247,
        en: "to keep in touch",
        nl: "contact houden",
        direction: "en-nl",
        skill: "receptief",
    },
    {
        id: 248,
        en: "venue",
        nl: "gelegenheid",
        direction: "en-nl",
        skill: "receptief",
    },
    {
        id: 249,
        en: "average",
        nl: "gemiddeld",
        direction: "en-nl",
        skill: "receptief",
    },
    {
        id: 250,
        en: "despite",
        nl: "ondanks",
        direction: "en-nl",
        skill: "receptief",
    },
    {
        id: 251,
        en: "generally",
        nl: "doorgaans",
        direction: "en-nl",
        skill: "receptief",
    },
    {
        id: 252,
        en: "mainly",
        nl: "voornamelijk",
        direction: "en-nl",
        skill: "receptief",
    },
    {
        id: 253,
        en: "afterwards",
        nl: "daarna",
        direction: "en-nl",
        skill: "receptief",
    },
    {
        id: 254,
        en: "concerned",
        nl: "bezorgd",
        direction: "en-nl",
        skill: "receptief",
    },
    {
        id: 255,
        en: "proper",
        nl: "echt",
        direction: "en-nl",
        skill: "receptief",
    },
    {
        id: 256,
        en: "unless",
        nl: "tenzij",
        direction: "en-nl",
        skill: "receptief",
    },
    {
        id: 257,
        en: "department",
        nl: "afdeling",
        direction: "en-nl",
        skill: "receptief",
    },
    {
        id: 258,
        en: "experience",
        nl: "ervaring",
        direction: "en-nl",
        skill: "receptief",
    },
    {
        id: 259,
        en: "responsible",
        nl: "verantwoordelijk",
        direction: "en-nl",
        skill: "receptief",
    },
    {
        id: 260,
        en: "career",
        nl: "carrière",
        direction: "nl-en",
        skill: "productief",
    },
    {
        id: 261,
        en: "to continue",
        nl: "doorgaan met",
        direction: "nl-en",
        skill: "productief",
    },
    {
        id: 262,
        en: "curious",
        nl: "nieuwsgierig",
        direction: "nl-en",
        skill: "productief",
    },
    {
        id: 263,
        en: "during",
        nl: "tijdens",
        direction: "nl-en",
        skill: "productief",
    },
    {
        id: 264,
        en: "job",
        nl: "baan",
        direction: "nl-en",
        skill: "productief",
    },
    {
        id: 265,
        en: "to perform",
        nl: "optreden",
        direction: "nl-en",
        skill: "productief",
    },
    {
        id: 266,
        en: "quite",
        nl: "best wel",
        direction: "nl-en",
        skill: "productief",
    },
    {
        id: 267,
        en: "to receive",
        nl: "ontvangen",
        direction: "nl-en",
        skill: "productief",
    },
    {
        id: 268,
        en: "to sell",
        nl: "verkopen",
        direction: "nl-en",
        skill: "productief",
    },
    {
        id: 269,
        en: "uncomfortable",
        nl: "ongemakkelijk",
        direction: "nl-en",
        skill: "productief",
    },
    {
        id: 270,
        en: "to use",
        nl: "gebruiken",
        direction: "nl-en",
        skill: "productief",
    },
    {
        id: 271,
        en: "amazing",
        nl: "geweldig",
        direction: "nl-en",
        skill: "productief",
    },
    {
        id: 272,
        en: "beat",
        nl: "verslaan",
        direction: "nl-en",
        skill: "productief",
    },
    {
        id: 273,
        en: "clever",
        nl: "slim",
        direction: "nl-en",
        skill: "productief",
    },
    {
        id: 274,
        en: "compete",
        nl: "strijden",
        direction: "nl-en",
        skill: "productief",
    },
    {
        id: 275,
        en: "deal",
        nl: "afspraak",
        direction: "nl-en",
        skill: "productief",
    },
    {
        id: 276,
        en: "to joke",
        nl: "een grap maken",
        direction: "nl-en",
        skill: "productief",
    },
    {
        id: 277,
        en: "look forward to",
        nl: "naar iets uitzien",
        direction: "nl-en",
        skill: "productief",
    },
    {
        id: 278,
        en: "million",
        nl: "miljoen",
        direction: "nl-en",
        skill: "productief",
    },
    {
        id: 279,
        en: "shelf",
        nl: "plank",
        direction: "nl-en",
        skill: "productief",
    },
    {
        id: 280,
        en: "understand",
        nl: "begrijpen",
        direction: "nl-en",
        skill: "productief",
    },
    {
        id: 281,
        en: "to write down",
        nl: "opschrijven",
        direction: "nl-en",
        skill: "productief",
    },
    {
        id: 282,
        en: "age",
        nl: "leeftijd",
        direction: "nl-en",
        skill: "productief",
    },
    {
        id: 283,
        en: "besides",
        nl: "behalve",
        direction: "nl-en",
        skill: "productief",
    },
    {
        id: 284,
        en: "chance",
        nl: "kans",
        direction: "nl-en",
        skill: "productief",
    },
    {
        id: 285,
        en: "to design",
        nl: "ontwerpen",
        direction: "nl-en",
        skill: "productief",
    },
    {
        id: 286,
        en: "different",
        nl: "verschillend",
        direction: "nl-en",
        skill: "productief",
    },
    {
        id: 287,
        en: "enough",
        nl: "genoeg",
        direction: "nl-en",
        skill: "productief",
    },
    {
        id: 288,
        en: "furniture",
        nl: "meubels",
        direction: "nl-en",
        skill: "productief",
    },
    {
        id: 289,
        en: "important",
        nl: "belangrijk",
        direction: "nl-en",
        skill: "productief",
    },
    {
        id: 290,
        en: "pretty",
        nl: "mooi",
        direction: "nl-en",
        skill: "productief",
    },
    {
        id: 291,
        en: "screen",
        nl: "scherm",
        direction: "nl-en",
        skill: "productief",
    },
    {
        id: 292,
        en: "to touch",
        nl: "aanraken",
        direction: "nl-en",
        skill: "productief",
    },
    {
        id: 293,
        en: "without",
        nl: "zonder",
        direction: "nl-en",
        skill: "productief",
    },
    {
        id: 294,
        en: "showbizz",
        nl: "showbiz",
        direction: "nl-en",
        skill: "productief",
    },
    {
        id: 295,
        en: "entertainment",
        nl: "entertainment",
        direction: "nl-en",
        skill: "productief",
    },
    {
        id: 296,
        en: "linking words",
        nl: "voegwoorden",
        direction: "nl-en",
        skill: "productief",
    },
    {
        id: 297,
        en: "also",
        nl: "ook",
        direction: "nl-en",
        skill: "productief",
    },
    {
        id: 298,
        en: "to applaud",
        nl: "applauddiseren",
        direction: "nl-en",
        skill: "productief",
    },
    {
        id: 299,
        en: "audience",
        nl: "publiek",
        direction: "nl-en",
        skill: "productief",
    },
    {
        id: 300,
        en: "autograph",
        nl: "handtekening",
        direction: "nl-en",
        skill: "productief",
    },
    {
        id: 301,
        en: "backstage",
        nl: "achter de schermen",
        direction: "nl-en",
        skill: "productief",
    },
    {
        id: 302,
        en: "because",
        nl: "omdat",
        direction: "nl-en",
        skill: "productief",
    },
    {
        id: 303,
        en: "breakthrough",
        nl: "doorbraak",
        direction: "nl-en",
        skill: "productief",
    },
    {
        id: 304,
        en: "but",
        nl: "maar",
        direction: "nl-en",
        skill: "productief",
    },
    {
        id: 305,
        en: "celebrity",
        nl: "beroemdheid",
        direction: "nl-en",
        skill: "productief",
    },
    {
        id: 306,
        en: "clearly",
        nl: "duidelijk",
        direction: "nl-en",
        skill: "productief",
    },
    {
        id: 307,
        en: "dressing room",
        nl: "kleedkamer",
        direction: "nl-en",
        skill: "productief",
    },
    {
        id: 308,
        en: "to entertain",
        nl: "vermaken",
        direction: "nl-en",
        skill: "productief",
    },
    {
        id: 309,
        en: "first",
        nl: "ten eerste",
        direction: "nl-en",
        skill: "productief",
    },
    {
        id: 310,
        en: "for example",
        nl: "bijvoorbeeld",
        direction: "nl-en",
        skill: "productief",
    },
    {
        id: 311,
        en: "glamorous",
        nl: "aantrekkelijk",
        direction: "nl-en",
        skill: "productief",
    },
    {
        id: 312,
        en: "to gossip",
        nl: "roddelen",
        direction: "nl-en",
        skill: "productief",
    },
    {
        id: 313,
        en: "however",
        nl: "echter",
        direction: "nl-en",
        skill: "productief",
    },
    {
        id: 314,
        en: "in fact",
        nl: "in feite",
        direction: "nl-en",
        skill: "productief",
    },
    {
        id: 315,
        en: "next",
        nl: "vervolgens",
        direction: "nl-en",
        skill: "productief",
    },
    {
        id: 316,
        en: "publicity",
        nl: "bekendheid",
        direction: "nl-en",
        skill: "productief",
    },
    {
        id: 317,
        en: "red carpet",
        nl: "rode loper",
        direction: "nl-en",
        skill: "productief",
    },
    {
        id: 318,
        en: "to rehearse",
        nl: "repeteren",
        direction: "nl-en",
        skill: "productief",
    },
    {
        id: 319,
        en: "review",
        nl: "recensie",
        direction: "nl-en",
        skill: "productief",
    },
    {
        id: 320,
        en: "since",
        nl: "aangezien",
        direction: "nl-en",
        skill: "productief",
    },
    {
        id: 321,
        en: "so",
        nl: "zodat",
        direction: "nl-en",
        skill: "productief",
    },
    {
        id: 322,
        en: "such as",
        nl: "zoals",
        direction: "nl-en",
        skill: "productief",
    },
    {
        id: 323,
        en: "therefore",
        nl: "daarom",
        direction: "nl-en",
        skill: "productief",
    },
    {
        id: 324,
        en: "too",
        nl: "ook",
        direction: "nl-en",
        skill: "productief",
    },
    {
        id: 325,
        en: "annoying",
        nl: "vervelend",
        direction: "nl-en",
        skill: "productief",
    },
    {
        id: 326,
        en: "expressing your opinion",
        nl: "je mening geven",
        direction: "nl-en",
        skill: "productief",
    },
    {
        id: 327,
        en: "awful",
        nl: "verschrikkelijk",
        direction: "nl-en",
        skill: "productief",
    },
    {
        id: 328,
        en: "charming",
        nl: "aantrekkelijk",
        direction: "nl-en",
        skill: "productief",
    },
    {
        id: 329,
        en: "disappointing",
        nl: "teleurstellend",
        direction: "nl-en",
        skill: "productief",
    },
    {
        id: 330,
        en: "impressive",
        nl: "indrukwekkend",
        direction: "nl-en",
        skill: "productief",
    },
    {
        id: 331,
        en: "moving",
        nl: "ontroerend",
        direction: "nl-en",
        skill: "productief",
    },
    {
        id: 332,
        en: "predictable",
        nl: "voorspelbaar",
        direction: "nl-en",
        skill: "productief",
    },
    {
        id: 333,
        en: "remarkable",
        nl: "opmerkelijk",
        direction: "nl-en",
        skill: "productief",
    },
    {
        id: 334,
        en: "silly",
        nl: "dwaas",
        direction: "nl-en",
        skill: "productief",
    },
    {
        id: 335,
        en: "surprising",
        nl: "verrassend",
        direction: "nl-en",
        skill: "productief",
    },
    {
        id: 336,
        en: "terrible",
        nl: "verschrikkelijk",
        direction: "nl-en",
        skill: "productief",
    },
    {
        id: 337,
        en: "thrilling",
        nl: "spannend",
        direction: "nl-en",
        skill: "productief",
    },
    {
        id: 338,
        en: "weird",
        nl: "raar",
        direction: "nl-en",
        skill: "productief",
    },
    {
        id: 339,
        en: "wonderful",
        nl: "geweldig",
        direction: "nl-en",
        skill: "productief",
    },
    {
        id: 340,
        en: "blockbuster",
        nl: "kaskraker",
        direction: "nl-en",
        skill: "productief",
    },
    {
        id: 341,
        en: "cast",
        nl: "rolverdeling",
        direction: "nl-en",
        skill: "productief",
    },
    {
        id: 342,
        en: "director",
        nl: "regisseur",
        direction: "nl-en",
        skill: "productief",
    },
    {
        id: 343,
        en: "episode",
        nl: "aflevering",
        direction: "nl-en",
        skill: "productief",
    },
    {
        id: 344,
        en: "extra",
        nl: "figurant",
        direction: "nl-en",
        skill: "productief",
    },
    {
        id: 345,
        en: "preview",
        nl: "voorvertoning",
        direction: "nl-en",
        skill: "productief",
    },
    {
        id: 346,
        en: "to rate",
        nl: "waarderen",
        direction: "nl-en",
        skill: "productief",
    },
    {
        id: 347,
        en: "remake",
        nl: "nieuwe versie",
        direction: "nl-en",
        skill: "productief",
    },
    {
        id: 348,
        en: "screenplay",
        nl: "scenario",
        direction: "nl-en",
        skill: "productief",
    },
    {
        id: 349,
        en: "to shoot (a film)",
        nl: "filmen",
        direction: "nl-en",
        skill: "productief",
    },
    {
        id: 350,
        en: "to star",
        nl: "de hoofdrol spelen",
        direction: "nl-en",
        skill: "productief",
    },
    {
        id: 351,
        en: "storyline",
        nl: "verhaallijn",
        direction: "nl-en",
        skill: "productief",
    },
    {
        id: 352,
        en: "subtitles",
        nl: "ondertiteling",
        direction: "nl-en",
        skill: "productief",
    },
    //Chapter 4
];