export const WORDS = [
    {
        id: 1,
        en: "bored",
        nl: "verveeld",
        direction: "nl-en",      // of "en-nl"
        skill: "productief",     // of "receptief"
    },
    {
        id: 2,
        en: "culture",
        nl: "cultuur",
        direction: "nl-en",
        skill: "productief",
    },
    {
        id: 3,
        en: "gold",
        nl: "goud",
        direction: "nl-en",
        skill: "productief",
    },
    {
        id: 4,
        en: "to paint",
        nl: "schilderen",
        direction: "nl-en",
        skill: "productief",
    },
    {
        id: 5,
        en: "to prefer",
        nl: "voorkeur geven aan",
        direction: "nl-en",
        skill: "productief",
    },
    {
        id: 6,
        en: "probably",
        nl: "waarschijnlijk",
        direction: "nl-en",
        skill: "productief",
    },
    {
        id: 7,
        en: "ride",
        nl: "attractie",
        direction: "nl-en",
        skill: "productief",
    },
    {
        id: 8,
        en: "to serve",
        nl: "serveren",
        direction: "nl-en",
        skill: "productief",
    },
    {
        id: 9,
        en: "somewhere",
        nl: "ergens",
        direction: "nl-en",
        skill: "productief",
    },
    {
        id: 10,
        en: "to sweat",
        nl: "zweten",
        direction: "nl-en",
        skill: "productief",
    },
    {
        id: 11,
        en: "tiny",
        nl: "heel klein",
        direction: "nl-en",
        skill: "productief",
    },
    {
        id: 12,
        en: "frame",
        nl: "lijst",
        direction: "en-nl",
        skill: "receptief",
    },
    {
        id: 13,
        en: "portrait",
        nl: "portret",
        direction: "en-nl",
        skill: "receptief",
    },
    {
        id: 14,
        en: "tank",
        nl: "aquarium",
        direction: "en-nl",
        skill: "receptief",
    },
    {
        id: 15,
        en: "to vomit",
        nl: "overgeven",
        direction: "en-nl",
        skill: "receptief",
    },
    {
        id: 16,
        en: "cosy",
        nl: "gezellig",
        direction: "nl-en",
        skill: "productief",
    },
    {
        id: 17,
        en: "decide",
        nl: "beslissen",
        direction: "nl-en",
        skill: "productief",
    },
    {
        id: 18,
        en: "delicious",
        nl: "heerlijk",
        direction: "nl-en",
        skill: "productief",
    },
    {
        id: 19,
        en: "fashion",
        nl: "mode",
        direction: "nl-en",
        skill: "productief",
    },
    {
        id: 20,
        en: "hill",
        nl: "heuvel",
        direction: "nl-en",
        skill: "productief",
    },
    {
        id: 21,
        en: "incredible",
        nl: "ongelofelijk",
        direction: "nl-en",
        skill: "productief",
    },
    {
        id: 22,
        en: "loud",
        nl: "hard",
        direction: "nl-en",
        skill: "productief",
    },
    {
        id: 23,
        en: "noise",
        nl: "lawaai",
        direction: "nl-en",
        skill: "productief",
    },
    {
        id: 24,
        en: "scary",
        nl: "eng",
        direction: "nl-en",
        skill: "productief",
    },
    {
        id: 25,
        en: "view",
        nl: "uitzicht",
        direction: "nl-en",
        skill: "productief",
    },
    {
        id: 26,
        en: "bike lane",
        nl: "fietspad",
        direction: "en-nl",
        skill: "receptief",
    },
    {
        id: 27,
        en: "definitely",
        nl: "absoluut",
        direction: "en-nl",
        skill: "receptief",
    },
    {
        id: 28,
        en: "explore",
        nl: "onderzoeken",
        direction: "en-nl",
        skill: "receptief",
    },
    {
        id: 29,
        en: "several",
        nl: "verschillende",
        direction: "en-nl",
        skill: "receptief",
    },
    {
        id: 30,
        en: "to compare",
        nl: "vergelijken met",
        direction: "nl-en",
        skill: "productief",
    },
    {
        id: 31,
        en: "cushion",
        nl: "kussen",
        direction: "nl-en",
        skill: "productief",
    },
    {
        id: 32,
        en: "floor",
        nl: "verdieping",
        direction: "nl-en",
        skill: "productief",
    },
    {
        id: 33,
        en: "island",
        nl: "eiland",
        direction: "nl-en",
        skill: "productief",
    },
    {
        id: 34,
        en: "luckily",
        nl: "gelukkig",
        direction: "nl-en",
        skill: "productief",
    },
    {
        id: 35,
        en: "prepared",
        nl: "voorbereid",
        direction: "nl-en",
        skill: "productief",
    },
    {
        id: 36,
        en: "protect",
        nl: "beschermen",
        direction: "nl-en",
        skill: "productief",
    },
    {
        id: 37,
        en: "shade",
        nl: "schaduw",
        direction: "nl-en",
        skill: "productief",
    },
    {
        id: 38,
        en: "tradition",
        nl: "traditie",
        direction: "nl-en",
        skill: "productief",
    },
    {
        id: 39,
        en: "unique",
        nl: "uniek",
        direction: "nl-en",
        skill: "productief",
    },
    {
        id: 40,
        en: "boiling hot",
        nl: "gloeiend heet",
        direction: "en-nl",
        skill: "receptief",
    },
    {
        id: 41,
        en: "considering",
        nl: "gezien het feit dat",
        direction: "en-nl",
        skill: "receptief",
    },
    {
        id: 42,
        en: "get the hang of something",
        nl: "iets onder de knie krijgen",
        direction: "en-nl",
        skill: "receptief",
    },
    {
        id: 43,
        en: "moody",
        nl: "humeurig",
        direction: "en-nl",
        skill: "receptief",
    },
    {
        id: 44,
        en: "slightly",
        nl: "een beetje",
        direction: "en-nl",
        skill: "receptief",
    },
    {
        id: 45,
        en: "actually",
        nl: "eigenlijk",
        direction: "nl-en",
        skill: "productief",
    },
    {
        id: 46,
        en: "to climb",
        nl: "klimmen",
        direction: "nl-en",
        skill: "productief",
    },
    {
        id: 47,
        en: "fake",
        nl: "nep",
        direction: "nl-en",
        skill: "productief",
    },
    {
        id: 48,
        en: "flag",
        nl: "vlag",
        direction: "nl-en",
        skill: "productief",
    },
    {
        id: 49,
        en: "pretend",
        nl: "doen alsof",
        direction: "nl-en",
        skill: "productief",
    },
    {
        id: 50,
        en: "to reach",
        nl: "bereiken",
        direction: "nl-en",
        skill: "productief",
    },
    {
        id: 51,
        en: "realise",
        nl: "zich realiseren",
        direction: "nl-en",
        skill: "productief",
    },
    {
        id: 52,
        en: "rock",
        nl: "rots",
        direction: "nl-en",
        skill: "productief",
    },
    {
        id: 53,
        en: "save",
        nl: "redden",
        direction: "nl-en",
        skill: "productief",
    },
    {
        id: 54,
        en: "shadow",
        nl: "schaduw",
        direction: "nl-en",
        skill: "productief",
    },
    {
        id: 55,
        en: "terrifying",
        nl: "angstaanjagend",
        direction: "nl-en",
        skill: "productief",
    },
    {
        id: 56,
        en: "upside down",
        nl: "ondersteboven",
        direction: "nl-en",
        skill: "productief",
    },
    {
        id: 57,
        en: "to pose",
        nl: "poseren",
        direction: "en-nl",
        skill: "receptief",
    },
    {
        id: 58,
        en: "to trick",
        nl: "bedriegen",
        direction: "en-nl",
        skill: "receptief",
    },
    {
        id: 59,
        en: "truth",
        nl: "waarheid",
        direction: "en-nl",
        skill: "receptief",
    },
    {
        id: 60,
        en: "travelling",
        nl: "reizen",
        direction: "nl-en",
        skill: "productief",
    },
    {
        id: 61,
        en: "packing your suitcase",
        nl: "je koffer inpakken",
        direction: "nl-en",
        skill: "productief",
    },
    {
        id: 62,
        en: "to board",
        nl: "instappen",
        direction: "nl-en",
        skill: "productief",
    },
    {
        id: 63,
        en: "abroad",
        nl: "naar het buitenland",
        direction: "nl-en",
        skill: "productief",
    },
    {
        id: 64,
        en: "airport",
        nl: "luchthaven",
        direction: "nl-en",
        skill: "productief",
    },
    {
        id: 65,
        en: "arrival",
        nl: "aankomst",
        direction: "nl-en",
        skill: "productief",
    },
    {
        id: 66,
        en: "backpack",
        nl: "rugzak",
        direction: "nl-en",
        skill: "productief",
    },
    {
        id: 67,
        en: "beach towel",
        nl: "strandhanddoek",
        direction: "nl-en",
        skill: "productief",
    },
    {
        id: 68,
        en: "border",
        nl: "grens",
        direction: "nl-en",
        skill: "productief",
    },
    {
        id: 69,
        en: "campsite",
        nl: "camping",
        direction: "nl-en",
        skill: "productief",
    },
    {
        id: 70,
        en: "charger",
        nl: "oplader",
        direction: "nl-en",
        skill: "productief",
    },
    {
        id: 71,
        en: "check-in",
        nl: "incheckbalie",
        direction: "nl-en",
        skill: "productief",
    },
    {
        id: 72,
        en: "customs",
        nl: "douane",
        direction: "nl-en",
        skill: "productief",
    },
    {
        id: 73,
        en: "departure",
        nl: "vertrek",
        direction: "nl-en",
        skill: "productief",
    },
    {
        id: 74,
        en: "destination",
        nl: "bestemming",
        direction: "nl-en",
        skill: "productief",
    },
    {
        id: 75,
        en: "flight",
        nl: "vlucht",
        direction: "nl-en",
        skill: "productief",
    },
    {
        id: 75,
        en: "flight",
        nl: "vlucht",
        direction: "nl-en",
        skill: "productief",
    },
    {
        id: 76,
        en: "flip-flops",
        nl: "teenslippers",
        direction: "nl-en",
        skill: "productief",
    },
    {
        id: 77,
        en: "headphones",
        nl: "koptelefoon",
        direction: "nl-en",
        skill: "productief",
    },
    {
        id: 78,
        en: "luggage",
        nl: "bagage",
        direction: "nl-en",
        skill: "productief",
    },
    {
        id: 79,
        en: "passport",
        nl: "paspoort",
        direction: "nl-en",
        skill: "productief",
    },
    {
        id: 80,
        en: "rain coat",
        nl: "regenjas",
        direction: "nl-en",
        skill: "productief",
    },
    {
        id: 81,
        en: "sleeping bag",
        nl: "slaapzak",
        direction: "nl-en",
        skill: "productief",
    },
    {
        id: 82,
        en: "sunglasses",
        nl: "zonnebril",
        direction: "nl-en",
        skill: "productief",
    },
    {
        id: 83,
        en: "sunscreen",
        nl: "zonnebrandcrème",
        direction: "nl-en",
        skill: "productief",
    },
    {
        id: 84,
        en: "swimwear",
        nl: "badkleding",
        direction: "nl-en",
        skill: "productief",
    },
    {
        id: 85,
        en: "to take off",
        nl: "vertrekken",
        direction: "nl-en",
        skill: "productief",
    },
    {
        id: 86,
        en: "toothbrush",
        nl: "tandenborstel",
        direction: "nl-en",
        skill: "productief",
    },
    {
        id: 87,
        en: "toothpaste",
        nl: "tandpasta",
        direction: "nl-en",
        skill: "productief",
    },
    {
        id: 88,
        en: "travel guide",
        nl: "reisgids",
        direction: "nl-en",
        skill: "productief",
    },
    {
        id: 89,
        en: "trip",
        nl: "tocht",
        direction: "nl-en",
        skill: "productief",
    },
    {
        id: 90,
        en: "holiday activities",
        nl: "vakantieactiviteiten",
        direction: "nl-en",
        skill: "productief",
    },
    {
        id: 91,
        en: "to go backpacking",
        nl: "gaan rondtrekken",
        direction: "nl-en",
        skill: "productief",
    },
    {
        id: 92,
        en: "to go camping",
        nl: "gaan kamperen",
        direction: "nl-en",
        skill: "productief",
    },
    {
        id: 93,
        en: "to go sightseeing",
        nl: "bezienswaardigheden bezoeken",
        direction: "nl-en",
        skill: "productief",
    },
    {
        id: 94,
        en: "to hike",
        nl: "wandelen",
        direction: "nl-en",
        skill: "productief",
    },
    {
        id: 95,
        en: "to hit the beach",
        nl: "naar het strand gaan",
        direction: "nl-en",
        skill: "productief",
    },
    {
        id: 96,
        en: "to pitch your tent",
        nl: "je tent opzetten",
        direction: "nl-en",
        skill: "productief",
    },
    {
        id: 97,
        en: "to rent a bike",
        nl: "een fiets huren",
        direction: "nl-en",
        skill: "productief",
    },
    {
        id: 98,
        en: "to sign up for",
        nl: "inschrijven voor",
        direction: "nl-en",
        skill: "productief",
    },
    {
        id: 99,
        en: "to stay at",
        nl: "logeren",
        direction: "nl-en",
        skill: "productief",
    },
    {
        id: 100,
        en: "to sunbathe",
        nl: "zonnebaden",
        direction: "nl-en",
        skill: "productief",
    },
    {
        id: 101,
        en: "to take a dip",
        nl: "een duik nemen",
        direction: "nl-en",
        skill: "productief",
    },
    {
        id: 102,
        en: "to take a guided tour",
        nl: "een rondleiding krijgen",
        direction: "nl-en",
        skill: "productief",
    },
    {
        id: 103,
        en: "to take a picture",
        nl: "een foto maken",
        direction: "nl-en",
        skill: "productief",
    },
    {
        id: 104,
        en: "the weather",
        nl: "het weer",
        direction: "nl-en",
        skill: "productief",
    },
    {
        id: 105,
        en: "bright",
        nl: "helder",
        direction: "nl-en",
        skill: "productief",
    },
    {
        id: 106,
        en: "clear",
        nl: "helder",
        direction: "nl-en",
        skill: "productief",
    },
    {
        id: 107,
        en: "cloudy",
        nl: "bewolkt",
        direction: "nl-en",
        skill: "productief",
    },
    {
        id: 108,
        en: "fog",
        nl: "mist",
        direction: "nl-en",
        skill: "productief",
    },
    {
        id: 109,
        en: "hail",
        nl: "hagel",
        direction: "nl-en",
        skill: "productief",
    },
    {
        id: 110,
        en: "hurricane",
        nl: "orkaan",
        direction: "nl-en",
        skill: "productief",
    },
    {
        id: 111,
        en: "lightning",
        nl: "bliksem",
        direction: "nl-en",
        skill: "productief",
    },
    {
        id: 112,
        en: "rainbow",
        nl: "regenboog",
        direction: "nl-en",
        skill: "productief",
    },
    {
        id: 113,
        en: "rainy",
        nl: "regenachtig",
        direction: "nl-en",
        skill: "productief",
    },
    {
        id: 114,
        en: "rain shower",
        nl: "regenbui",
        direction: "nl-en",
        skill: "productief",
    },
    {
        id: 115,
        en: "stormy",
        nl: "stormachtig",
        direction: "nl-en",
        skill: "productief",
    },
    {
        id: 116,
        en: "sunny",
        nl: "zonnig",
        direction: "nl-en",
        skill: "productief",
    },
    {
        id: 117,
        en: "thunder",
        nl: "donder",
        direction: "nl-en",
        skill: "productief",
    },
    {
        id: 118,
        en: "windy",
        nl: "winderig",
        direction: "nl-en",
        skill: "productief",
    },
];