name: Deploy PartyGameWebClient to Azure App Service

on:
  push:
    branches:
      - release
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Deploy to Azure App Service
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'PartyGameWebClient'     # your App Service name
          package: '.'                        # deploy the root folder (index.html etc.)
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE }}
